routes/web.php
<?php

use App\Http\Controllers\VotesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('users/notifications','UsersController@notifications')->name('users.notifications');

Route::resource('questions','QuestionsController')->except('show');
Route::get('questions/{slug}','QuestionsController@show')->name('questions.show');

Route::post('questions/{question}/favorite','FavoritesController@store')->name('questions.favorite');
Route::delete('questions/{question}/unfavorite','FavoritesController@destroy')->name('questions.unfavorite');


Route::post('questions/{question}/vote/{vote}', 'VotesController@voteQuestion')->name('questions.vote');
Route::post('answers/{answer}/vote/{vote}', 'VotesController@voteAnswer')->name('answers.vote');

Route::resource('questions.answers','AnswersController')->except(['index','show','create']);
Route::put('answers/{answer}/best-answer','AnswersController@bestAnswer')->name('answers.bestAnswer');
Route::get('/home', 'HomeController@index')->name('home');

app/Answer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    protected $guarded = [];
    //
    public static function boot(){
        parent::boot();
        static::created(function($answer){
            $answer->question->increment('answers_count');
        });
        static::deleted(function($answer){
            $answer->question->decrement('answers_count');
        });
    }
    public function getCreatedDateAttribute(){
        return $this->created_at->diffForHumans();
    }
    public function getIsBestAttribute(){
        return $this->id===$this->question->best_answer_id;
    }
    public function getBestAnswerStatusAttribute(){
        if($this->id === $this->question->best_answer_id){
            return "text-success";
        }
        return "text-dark";
    }
    public function question(){
        return $this->belongsTo(Question::class);
    }
    public function author(){
        return $this->belongsTo(User::class,'user_id');
    }
    public function votes(){
        return $this->morphToMany(User::class,'vote')->withTimestamps();
    }


    public function vote(int $vote){
        $this->votes()->attach(auth()->id(),['vote'=>$vote]);
        if($vote < 0)
        {
            $this->decrement('votes_count');
        }
        else{
            $this->increment('votes_count');
        }
    }
    public function updateVote(int $vote)
    {
        //User may have already up-voted this question and now down votes (vote_count=10) and now user down votes (vote_count= 9) vote_count==8
        $this->votes()->updateExistingPivot(auth()->id(),['vote'=>$vote]);
        if($vote < 0)
        {
            $this->decrement('votes_count');
            $this->decrement('votes_count');
        }
        else
        {
            $this->increment('votes_count');
            $this->increment('votes_count');
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    /**
     * ACCESSORS
     * */
    public function getAvatarAttribute(){
        $size = 40;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}";
    }

    /**
     * Relationship methods
     */
    public function questions()
    {
        return $this->hasMany(Question::class);
    }
    public function answers() {
        return $this->hasMany(Answer::class);
    }
    public function favorites(){
        return $this->belongsToMany(Question::class)->withTimestamps();
    }

    public function voteQuestions()
    {
        return $this->morphedByMany(Question::class,'vote')->withTimestamps();
    }
    public function voteAnswers()
    {
        return $this->morphedByMany(Answer::class,'vote')->withTimestamps();
    }

    /**
     * HELPER FUNCTIONS
     */

    public function hasQuestionUpVote(Question $question){
        return auth()->user()->voteQuestions()->where(['vote'=>1,'vote_id'=>$question->id])->exists();
    }
    public function hasQuestionDownVote(Question $question){
        return auth()->user()->voteQuestions()->where(['vote'=>-1,'vote_id'=>$question->id])->exists();
    }
    public function hasVoteForQuestion(Question $question){
        return $this->hasQuestionUpVote($question) || $this->hasQuestionDownVote($question);
    }

    public function hasAnswerUpVote(Answer $answer){
        return auth()->user()->voteAnswers()->where(['vote'=>1,'vote_id'=>$answer->id])->exists();
    }
    public function hasAnswerDownVote(Answer $answer){
        return auth()->user()->voteAnswers()->where(['vote'=>-1,'vote_id'=>$answer->id])->exists();
    }
    public function hasVoteForAnswer(Answer $answer){
        return $this->hasAnswerUpVote($answer) || $this->hasAnswerDownVote($answer);
    }

}

app/Http/Controllers/AnswersController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use App\Question;
use App\Http\Requests\Answers\CreateAnswerRequest;
use App\Http\Requests\Answers\UpdateAnswerRequest;
use App\Notifications\NewReplyAdded;
use Illuminate\Http\Request;

class AnswersController extends Controller
{
    public function store(CreateAnswerRequest $request,Question $question)
    {
        $question->answers()->create([
            'body'=>$request->body,
            'user_id'=>auth()->id()
        ]);
        $question->owner->notify(new NewReplyAdded($question));
        session()->flash('success', 'Your answer submitted succesfully!');
        return redirect($question->url);
    }
    public function edit(Question $question,Answer $answer)
    {
        //
        $this->authorize('update',$answer);
        return view('answers.edit',compact([
            'question',
            'answer'
        ]));
    }
    public function update(UpdateAnswerRequest $request,Question $question, Answer $answer)
    {
        $answer->update([
            'body'=>$request->body
        ]);
        session()->flash('success', 'Your answer has been updated succesfully!');
        return redirect($question->url);
    }
    public function destroy(Question $question,Answer $answer)
    {
        //
        $this->authorize('delete',$answer);
        $answer->delete();
        session()->flash('success', 'Your answer has been deleted succesfully!');
        return redirect($question->url);
    }
    public function bestAnswer(Request $request,Answer $answer)
    {
        $this->authorize('markAsBest',$answer);
        $answer->question->markBestAnswer($answer);
        return redirect()->back();
    }
}

resources/views/answers/_create.blade.php
<div class="row mt-5">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3>Your Answer</h3>
            </div>
            <div class="card-body">
                <form action="{{ route('questions.answers.store', $question->id) }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <input id="body" type="hidden" name="body" value="{{ old('body') }}">
                        <trix-editor input="body"></trix-editor>
                        @error('body')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-outline-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/answers/_index.blade.php
<div class="row mt-4">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="mt-0">
                            {{ Str::plural('Answer', $question->answers_count) }}
                        </h3>
                    </div>
                    <div class="card-body">
                        @foreach($question->answers as $answer)
                            <div class="d-flex">
                                <div class="d-flex flex-column">
                                    <div>

@can('vote', $answer)
<form action="{{ route('answers.vote', [$answer->id, 1]) }}" method="POST">
    @csrf
    <button type="submit" class="btn {{ auth()->user()->hasAnswerUpVote($answer) ? 'text-dark': 'text-black-50' }}">
        <i class="fa fa-caret-up fa-3x" aria-hidden="true"></i>
    </button>
</form>
@else
<a href="{{ route('login') }}" title="Up Vote" class="vote-up d-block text-center text-black-50">
    <i class="fa fa-caret-up fa-3x" aria-hidden="true"></i>
</a>
@endcan
<h4 class="votes-count text-muted text-center m-0">{{ $answer->votes_count }}</h4>
@can('vote', $answer)
<form action="{{ route('answers.vote', [$answer->id, -1]) }}" method="POST">
    @csrf
    <button type="submit" class="btn {{ auth()->user()->hasAnswerDownVote($answer) ? 'text-dark': 'text-black-50' }}">
        <i class="fa fa-caret-down fa-3x" aria-hidden="true"></i>
    </button>
</form>
@else
<a href="{{ route('login') }}" title="Up Vote" class="vote-up d-block text-center text-black-50">
    <i class="fa fa-caret-up fa-3x" aria-hidden="true"></i>
</a>
@endcan
                                    </div>

                                    <div class="mt-2">
                                        @can('markAsBest',$answer)
                                            <form action="{{route('answers.bestAnswer',$answer->id)}}" method="POST">
                                                @csrf
                                                @method('PUT')
                                                <button type="submit" class="btn {{$answer->best_answer_status}}" title="Mark as best answer"><i class="fa fa-check fa-2x"></i></button>
                                            </form>
                                        @else
                                            @if($answer->is_best)
                                                <i class="fa fa-check fa-2x d-block text-success"></i>
                                            @endif
                                        @endcan
                                        <h4 class="votes-count m-0 text-center">123</h4>
                                    </div>
                                </div>
                                <div class="ml-5">
                                    {!! $answer->body !!}
                                </div>
                            </div>
                            <div class="d-flex justify-content-between mr-3">
                                <div>
                                    @can('update',$answer)
                                        <a href="{{route('questions.answers.edit',[$question->id,$answer->id]) }}"
                                            class="btn btn-outline-info">Edit</a>
                                    @endcan
                                    @can('delete',$answer)
                                        <form action="{{route('questions.answers.destroy',[$question->id,$answer->id]) }}"
                                            method="POST" class="d-inline">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" onclick="return confirm('Are you sure?')" class="btn btn-outline-danger">Delete</button>

                                        </form>
                                    @endcan
                                </div>
                                <div class="d-flex flex-column">
                                    <div class="text-muted mb-2 text-right">
                                        Answered {{ $answer->created_date }}
                                    </div>
                                    <div class="d-flex mb-2">
                                        <div>
                                            <img src="{{ $answer->author->avatar }}" alt="">
                                        </div>
                                        <div class="mt-2 ml-2">
                                            {{ $answer->author->name }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>

resources/views/answers/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3>Your Answer</h3>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('questions.answers.update', [$question->id,$answer->id]) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <input id="body" type="hidden" name="body" value="{{ old('body',$answer->body) }}">
                                <trix-editor input="body"></trix-editor>
                                @error('body')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
@endsection

@section('styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
@endsection