routes/web.php
<?php

use App\Http\Controllers\VotesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('users/notifications','UsersController@notifications')->name('users.notifications');

Route::resource('questions','QuestionsController')->except('show');
Route::get('questions/{slug}','QuestionsController@show')->name('questions.show');

Route::post('questions/{question}/favorite','FavoritesController@store')->name('questions.favorite');
Route::delete('questions/{question}/unfavorite','FavoritesController@destroy')->name('questions.unfavorite');


Route::post('questions/{question}/vote/{vote}', 'VotesController@voteQuestion')->name('questions.vote');
Route::post('answers/{answer}/vote/{vote}', 'VotesController@voteAnswer')->name('answers.vote');

Route::resource('questions.answers','AnswersController')->except(['index','show','create']);
Route::put('answers/{answer}/best-answer','AnswersController@bestAnswer')->name('answers.bestAnswer');
Route::get('/home', 'HomeController@index')->name('home');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use App\Answer;
class Question extends Model
{
    //
    protected $fillable = ['title','body'];
    protected $gaurded = [];

    public function owner()
    {
        return $this->belongsTo(User::class,'user_id');
    }
    public function setTitleAttribute($title)
    {
        $this->attributes['title'] = $title;
        $this->attributes['slug'] = Str::slug($title);
    }
    public function getUrlAttribute(){
        return "questions/{$this->slug}";
    }
    public function getCreatedDateAttribute(){
        return $this->created_at->diffForHumans();
    }
    public function getAnswersStyleAttribute(){
        if($this->answers_count > 0){
            if($this->best_answer_id){
                return "has-best-answer";
            }
            return "answered";
        }
        return "unanswered";
    }
    public function getFavoritesCountAttribute(){
        return $this->favorites->count();
    }
    public function getIsFavoriteAttribute(){
        return $this->favorites()->where(['user_id'=>auth()->id()])->count() > 0;
    }
    /**
     * ReLationship methods
     */
    public function answers() {
        return $this->hasMany(Answer::class);
    }
    public function markBestAnswer(Answer $answer){
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    public function favorites(){
        return $this->belongsToMany(User::class)->withTimestamps();
    }
    public function votes(){
        return $this->morphToMany(User::class,'vote')->withTimestamps();
    }

    public function vote(int $vote){
        $this->votes()->attach(auth()->id(),['vote'=>$vote]);
        if($vote < 0)
        {
            $this->decrement('votes_count');
        }
        else{
            $this->increment('votes_count');
        }
    }
    public function updateVote(int $vote)
    {
        //User may have already up-voted this question and now down votes (vote_count=10) and now user down votes (vote_count= 9) vote_count==8
        $this->votes()->updateExistingPivot(auth()->id(),['vote'=>$vote]);
        if($vote < 0)
        {
            $this->decrement('votes_count');
            $this->decrement('votes_count');
        }
        else
        {
            $this->increment('votes_count');
            $this->increment('votes_count');
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    /**
     * ACCESSORS
     * */
    public function getAvatarAttribute(){
        $size = 40;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}";
    }

    /**
     * Relationship methods
     */
    public function questions()
    {
        return $this->hasMany(Question::class);
    }
    public function answers() {
        return $this->hasMany(Answer::class);
    }
    public function favorites(){
        return $this->belongsToMany(Question::class)->withTimestamps();
    }

    public function voteQuestions()
    {
        return $this->morphedByMany(Question::class,'vote')->withTimestamps();
    }
    public function voteAnswers()
    {
        return $this->morphedByMany(Answer::class,'vote')->withTimestamps();
    }

    /**
     * HELPER FUNCTIONS
     */

    public function hasQuestionUpVote(Question $question){
        return auth()->user()->voteQuestions()->where(['vote'=>1,'vote_id'=>$question->id])->exists();
    }
    public function hasQuestionDownVote(Question $question){
        return auth()->user()->voteQuestions()->where(['vote'=>-1,'vote_id'=>$question->id])->exists();
    }
    public function hasVoteForQuestion(Question $question){
        return $this->hasQuestionUpVote($question) || $this->hasQuestionDownVote($question);
    }

    public function hasAnswerUpVote(Answer $answer){
        return auth()->user()->voteAnswers()->where(['vote'=>1,'vote_id'=>$answer->id])->exists();
    }
    public function hasAnswerDownVote(Answer $answer){
        return auth()->user()->voteAnswers()->where(['vote'=>-1,'vote_id'=>$answer->id])->exists();
    }
    public function hasVoteForAnswer(Answer $answer){
        return $this->hasAnswerUpVote($answer) || $this->hasAnswerDownVote($answer);
    }

}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Question;
use App\Http\Requests\Questions\CreateQuestionRequest;
use App\Http\Requests\Questions\UpdateQuestionRequest;
use Illuminate\Support\Facades\Gate;
use Illuminate\Http\Request;

class QuestionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware(['auth'])->only(['create','store','edit','update']);
    }
    public function index()
    {
        //
        $questions = Question::with('owner')->latest()->paginate(10);
        return view('questions.index',compact([
            'questions'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        app('debugbar')->disable();
        return view('questions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateQuestionRequest $request)
    {
        auth()->user()->questions()->create([
            'title'=>$request->title,
            'body'=>$request->body
        ]);
        
        session()->flash('success','Question has inserted successfully');
        return redirect(route('questions.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    // public function show($slug)
    // {
    //     $question = Question::where('slug',$slug)->firstOrFail();
    // }
    public function show(Question $question)
    {
        $question->increment('views_count');
        return view('questions.show',compact([
            'question'
        ]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question)
    {
        //first way to use Gate
        if($this->authorize('update',$question)){
            app('debugbar')->disable();
            return view('questions.edit',compact([
                'question'
            ]));
        }
        abort(403);
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateQuestionRequest $request, Question $question)
    {
        if($this->authorize('update',$question)){
            $question->update([
                'title'=>$request->title,
                'body'=>$request->body
            ]);
            session()->flash('success','Question has updated successfully');
            return redirect(route('questions.index'));    
        }
        abort(403);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Question  $question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question)
    {
        //second way to use Gate
        if($this->authorize('delete',$question)){
            $question->delete();
            session()->flash('success','Question has been deleted successfully');
            return redirect(route('questions.index'));
        }
        abort(403);
    }
    
}

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h3>Ask a Question</h3></div>
                    <div class="card-body">
                        <form action="{{ route('questions.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text"
                                       id="title"
                                       name="title"
                                       placeholder="Enter Title"
                                       value = "{{ old('title') }}"
                                       class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}">
                                @error('title')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <input id="body" type="hidden" name="body" value="{{ old('body') }}">
                                <trix-editor input="body"></trix-editor>
                                @error('body')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-success">Post a Question!</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
@endsection

@section('styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h3>Edit your Question</h3></div>
                    <div class="card-body">
                        <form action="{{ route('questions.update',$question->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text"
                                       id="title"
                                       name="title"
                                       placeholder="Enter Title"
                                       value = "{{ old('title',$question->title) }}"
                                       class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}">
                                @error('title')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <input id="body" type="hidden" name="body" value="{{ old('body',$question->body) }}">
                                <trix-editor input="body"></trix-editor>
                                @error('body')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-success">Edit a Question!</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
@endsection

@section('styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="d-flex justify-content-end mb-3">
                    <a href="{{ route('questions.create') }}" class="btn btn-outline-primary">Ask a Question!</a>
                </div>
                <div class="card">
                    <div class="card-header">All Questions</div>
                    @foreach($questions as $question)
                        <div class="card-body">
                            <div class="media">
                                <div class="d-flex flex-column statistics">
                                    <div class="votes text-center mb-3">
                                        <strong class="d-block">{{$question->votes_count}}</strong>
                                        Votes
                                    </div>
                                    <div class="answers text-center mb-3">
                                        <strong class="d-block answers {{$question->answers_style}}">{{$question->answers_count}}</strong>
                                        Answers
                                    </div>
                                    <div class="views text-center mb-3">
                                        <strong class="d-block">{{$question->views_count}}</strong>
                                        Views
                                    </div>
                                </div>
                                <div class="media-body">
                                    <div class="d-flex justify-content-between">
                                        <h4>
                                            <a href="{{$question->url}}">{{$question->title}}</a>   
                                        </h4>
                                        <div>
                                            <div class="d-flex">
                                                @can('update',$question)
                                                    <div class="mr-2">
                                                        <a href="{{route('questions.edit',$question->id)}}" class="btn btn-sm btn-outline-info">Edit</a>
                                                    </div>
                                                @endcan
                                                @can('delete',$question)
                                                    <form action="{{route('questions.destroy',$question->id)}}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" onclick="return confirm('Are you sure you want to delete')" class="btn btn-sm btn-outline-danger">Delete</button>
                                                    </form>
                                                @endcan
                                            </div>
                                            
                                        </div>
                                    </div>
                                    <p>
                                        Asked By: <a href="#">{{$question->owner->name}}</a>
                                        <span class="text-muted">| Asked: {{$question->created_date}}</span>
                                    </p>
                                    <p>{!!Str::limit($question->body,250)!!}</p>
                                </div>
                            </div>
                        </div>
                    @endforeach
                    <div class="card-footer">
                        {{$questions->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h1>{{ $question->title }}</h1>
                    </div>
                    <div class="card-body">
                        {!! $question->body !!}
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-between mr-3">
                            <div class="d-flex">
                                <div>
                                    @can('vote', $question)
                                        <form action="{{ route('questions.vote', [$question->id, 1]) }}" method="POST">
                                            @csrf
                                            <button type="submit" class="btn {{ auth()->user()->hasQuestionUpVote($question) ? 'text-dark': 'text-black-50' }}">
                                                <i class="fa fa-caret-up fa-3x" aria-hidden="true"></i>
                                            </button>
                                        </form>
                                    @else
                                        <a href="{{ route('login') }}" title="Up Vote" class="vote-up d-block text-center text-black-50">
                                            <i class="fa fa-caret-up fa-3x" aria-hidden="true"></i>
                                        </a>
                                    @endcan
                                    <h4 class="votes-count text-muted text-center m-0">{{ $question->votes_count }}</h4>
                                    @can('vote', $question)
                                        <form action="{{ route('questions.vote', [$question->id, -1]) }}" method="POST">
                                            @csrf
                                            <button type="submit" class="btn {{ auth()->user()->hasQuestionDownVote($question) ? 'text-dark': 'text-black-50' }}">
                                                <i class="fa fa-caret-down fa-3x" aria-hidden="true"></i>
                                            </button>
                                        </form>
                                    @else
                                        <a href="{{ route('login') }}" title="Up Vote" class="vote-up d-block text-center text-black-50">
                                            <i class="fa fa-caret-up fa-3x" aria-hidden="true"></i>
                                        </a>
                                    @endcan
                                </div>

                            <div class="ml-5 mt-2 {{$question->is_favorite ? 'text-warning' : 'text-black-50'}}">
                                @can('markAsFavorite',$question)
                            <form action="{{route($question->is_favorite?'questions.unfavorite': 'questions.favorite',$question->id)}}" method="POST">
                                @csrf
                                @if($question->is_favorite)
                                    @method('DELETE')
                                @endif
                            <button type="submit" class="btn  {{$question->is_favorite ? 'text-warning' : 'text-black-50'}}">
                               <i class="fa {{$question->is_favorite ? 'fa-star' : 'fa-star-o'}} fa-2x" aria-hidden="true"></i>
                            </button>
                            </form>
                        <h4 class="votes-count m-0 text-center">{{$question->favorites_count}}</h4>
                        @else
                            <i class="fa fa-star-o fa-2x text-black-50" aria-hidden="true"></i>
                        <h4 class="votes-count m-0 text-center text-black-50">{{$question->favorites_count}}</h4>
                            @endcan
                                </div>
                            </div>
                            <div class="d-flex flex-column">
                                <div class="text-muted mb-2 text-right">
                                    Asked {{ $question->created_date }}
                                </div>
                                <div class="d-flex mb-2">
                                    <div>
                                        <img src="{{ $question->owner->avatar }}" alt="">
                                    </div>
                                    <div class="mt-2 ml-2">
                                        {{ $question->owner->name }}
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!--ANSWERS-->
        @include('answers._index')
        @include('answers._create')
    </div>
@endsection
@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.js"></script>
@endsection